"""tools.py - Tool definitions for MiniRAG"""

from search_utils import SEARCH_FILES_TOOL, SEARCH_FILENAMES_TOOL, SEMANTIC_SEARCH_TOOL

TOOLS = [SEARCH_FILES_TOOL, SEARCH_FILENAMES_TOOL, SEMANTIC_SEARCH_TOOL]